services:
  dotfiles:
    build:
      context: .
      dockerfile: dockerfile
      args:
        USERNAME: user
    container_name: dotfiles-dev
    volumes:
      - .:/home/${USERNAME}/dotfiles
      - ~/.ssh:/home/${USERNAME}/.ssh:ro
    environment:
      - TERM=xterm-256color
    tty: true
    stdin_open: true
    command: bash

