services:
  dev: # サービス名
    build:
      context: .
      dockerfile: dockerfile
      args:
        USERNAME: ${USERNAME} # ユーザ名
    image: ${IMAGE_NAME} # イメージ名
    container_name: ${CONTAINER_NAME} # コンテナ名
    volumes:
      # ホスト機より.sshファイルを取得（entrypoint.shでコピー）
      - ~/.ssh:/home/${USERNAME}/.ssh-host:ro
    environment:
      - TERM=xterm-256color
    tty: true
    stdin_open: true
    command: bash

