services:
  dev: # サービス名
    build:
      context: .
      dockerfile: dockerfile
      args:
        USERNAME: ${USERNAME} # ユーザ名
    image: ${IMAGE_NAME} # イメージ名
    container_name: ${CONTAINER_NAME} # コンテナ名
    volumes:
      - ~/.ssh/known_hosts:/home/${USERNAME}/.ssh/known_hosts:ro
      - ${SSH_SOCK_PATH}:/ssh-agent:ro
    environment:
      - TERM=xterm-256color
      - SSH_AUTH_SOCK=/ssh-agent
    tty: true
    stdin_open: true
    command: bash

